# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firewallGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 680)
        MainWindow.setMinimumSize(QtCore.QSize(800, 680))
        MainWindow.setMaximumSize(QtCore.QSize(800, 680))
        MainWindow.setStyleSheet("background-color:#009999;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 10, 141, 31))
        self.label.setStyleSheet("font-size:18px;\n"
"font-weight:bold;")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 741, 151))
        self.groupBox.setStyleSheet("border:3px solid white;\n"
"font-size:15px;\n"
"background-color:#336699;\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.comboBoxChain = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxChain.setGeometry(QtCore.QRect(40, 60, 91, 31))
        self.comboBoxChain.setStyleSheet("border:none;\n"
"background-color:white;\n"
"color:black;")
        self.comboBoxChain.setFrame(False)
        self.comboBoxChain.setObjectName("comboBoxChain")
        self.comboBoxChain.addItem("")
        self.comboBoxChain.addItem("")
        self.comboBoxChain.addItem("")
        self.comboBoxChain.addItem("")
        self.comboBoxOption = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxOption.setGeometry(QtCore.QRect(190, 60, 91, 31))
        self.comboBoxOption.setStyleSheet("border:none;\n"
"background-color:white;\n"
"padding-left:10px;\n"
"color:black;")
        self.comboBoxOption.setObjectName("comboBoxOption")
        self.comboBoxOption.addItem("")
        self.comboBoxOption.addItem("")
        self.comboBoxOption.addItem("")
        self.comboBoxProtocol = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxProtocol.setGeometry(QtCore.QRect(340, 60, 81, 31))
        self.comboBoxProtocol.setStyleSheet("border:none;\n"
"background-color:white;\n"
"padding-left:10px;\n"
"color:black;")
        self.comboBoxProtocol.setObjectName("comboBoxProtocol")
        self.comboBoxProtocol.addItem("")
        self.comboBoxProtocol.addItem("")
        self.comboBoxProtocol.addItem("")
        self.comboBoxProtocol.addItem("")
        self.comboBoxAction = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxAction.setGeometry(QtCore.QRect(610, 60, 91, 31))
        self.comboBoxAction.setStyleSheet("background-color:white;\n"
"border:none;\n"
"padding-left:10px;\n"
"color:black;")
        self.comboBoxAction.setObjectName("comboBoxAction")
        self.comboBoxAction.addItem("")
        self.comboBoxAction.addItem("")
        self.comboBoxAction.addItem("")
        self.comboBoxAction.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 61, 16))
        self.label_2.setStyleSheet("border:none;\n"
"font-size:20px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(200, 30, 61, 21))
        self.label_3.setStyleSheet("border:none;\n"
"font-size:20px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(340, 30, 81, 31))
        self.label_4.setStyleSheet("border:none;\n"
"font-size:20px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(620, 30, 61, 16))
        self.label_5.setStyleSheet("border:none;\n"
"font-size:20px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.btn_create = QtWidgets.QPushButton(self.groupBox)
        self.btn_create.setGeometry(QtCore.QRect(610, 100, 91, 31))
        self.btn_create.setStyleSheet("background-color: #009933;\n"
"border:none;\n"
"border-radius:10px;\n"
"color:white;")
        self.btn_create.setObjectName("btn_create")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(500, 30, 61, 31))
        self.label_8.setStyleSheet("border:none;\n"
"font-size:20px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.spinBoxPort = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxPort.setGeometry(QtCore.QRect(480, 60, 81, 31))
        self.spinBoxPort.setStyleSheet("background-color:white;\n"
"border:none;\n"
"padding-left:5px;\n"
"color:black;")
        self.spinBoxPort.setMaximum(99999)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.comboBoxChain.raise_()
        self.comboBoxOption.raise_()
        self.comboBoxAction.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.btn_create.raise_()
        self.label_8.raise_()
        self.comboBoxProtocol.raise_()
        self.spinBoxPort.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 260, 741, 391))
        self.groupBox_2.setStyleSheet("border:3px solid white;\n"
"font-size:15px;\n"
"background-color:#336699;\n"
"font:white;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBoxRead = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxRead.setGeometry(QtCore.QRect(40, 40, 91, 31))
        self.comboBoxRead.setStyleSheet("border:none;\n"
"color:black;\n"
"background-color:white;\n"
"")
        self.comboBoxRead.setFrame(False)
        self.comboBoxRead.setObjectName("comboBoxRead")
        self.comboBoxRead.addItem("")
        self.comboBoxRead.addItem("")
        self.comboBoxRead.addItem("")
        self.btn_display = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_display.setGeometry(QtCore.QRect(220, 40, 91, 31))
        self.btn_display.setStyleSheet("background-color:#ff9900;\n"
"border:none;\n"
"border-radius:10px;\n"
"color:white;")
        self.btn_display.setObjectName("btn_display")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(40, 90, 661, 181))
        self.scrollArea.setStyleSheet("border:none;\n"
"background-color:#85adad;\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 661, 181))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 651, 192))
        self.tableWidget.setMaximumSize(QtCore.QSize(651, 16777215))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(208)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btn_delete = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_delete.setGeometry(QtCore.QRect(610, 330, 91, 31))
        self.btn_delete.setStyleSheet("border:none;\n"
"background-color:#cc0000;\n"
"border-radius:10px;\n"
"color:white;")
        self.btn_delete.setObjectName("btn_delete")
        self.spinBoxSelection = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxSelection.setGeometry(QtCore.QRect(491, 331, 61, 31))
        self.spinBoxSelection.setStyleSheet("background-color:white;\n"
"border:none;\n"
"padding-left:5px;\n"
"color:black;")
        self.spinBoxSelection.setObjectName("spinBoxSelection")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(40, 330, 301, 21))
        self.label_6.setStyleSheet("font-size:13px;\n"
"border:none;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(40, 250, 661, 61))
        self.label_7.setStyleSheet("font-size:25px;\n"
"border:none;\n"
"font-weight:bold;")
        self.label_7.setObjectName("label_7")
        self.comboBoxRead.raise_()
        self.btn_display.raise_()
        self.btn_delete.raise_()
        self.spinBoxSelection.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Firewall personnalisé"))
        self.label.setText(_translate("MainWindow", "MY FIREWALL"))
        self.groupBox.setTitle(_translate("MainWindow", "CREATE RULE"))
        self.comboBoxChain.setItemText(0, _translate("MainWindow", "--"))
        self.comboBoxChain.setItemText(1, _translate("MainWindow", "INPUT"))
        self.comboBoxChain.setItemText(2, _translate("MainWindow", "OUTPUT"))
        self.comboBoxChain.setItemText(3, _translate("MainWindow", "FORWARD"))
        self.comboBoxOption.setItemText(0, _translate("MainWindow", "--"))
        self.comboBoxOption.setItemText(1, _translate("MainWindow", "-A"))
        self.comboBoxOption.setItemText(2, _translate("MainWindow", "-I"))
        self.comboBoxProtocol.setItemText(0, _translate("MainWindow", "--"))
        self.comboBoxProtocol.setItemText(1, _translate("MainWindow", "tcp"))
        self.comboBoxProtocol.setItemText(2, _translate("MainWindow", "udp"))
        self.comboBoxProtocol.setItemText(3, _translate("MainWindow", "icmp"))
        self.comboBoxAction.setItemText(0, _translate("MainWindow", "--"))
        self.comboBoxAction.setItemText(1, _translate("MainWindow", "ACCEPT"))
        self.comboBoxAction.setItemText(2, _translate("MainWindow", "REJECT"))
        self.comboBoxAction.setItemText(3, _translate("MainWindow", "DROP"))
        self.label_2.setText(_translate("MainWindow", "chain"))
        self.label_3.setText(_translate("MainWindow", "option"))
        self.label_4.setText(_translate("MainWindow", "protocol"))
        self.label_5.setText(_translate("MainWindow", "action"))
        self.btn_create.setText(_translate("MainWindow", "CREATE"))
        self.label_8.setText(_translate("MainWindow", "port"))
        self.groupBox_2.setTitle(_translate("MainWindow", "READ OR DELETE A RULE"))
        self.comboBoxRead.setItemText(0, _translate("MainWindow", "INPUT"))
        self.comboBoxRead.setItemText(1, _translate("MainWindow", "OUTPUT"))
        self.comboBoxRead.setItemText(2, _translate("MainWindow", "FORWARD"))
        self.btn_display.setText(_translate("MainWindow", "DISPLAY"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Target"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Port"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Protocol"))
        self.btn_delete.setText(_translate("MainWindow", "DELETE"))
        self.label_6.setText(_translate("MainWindow", "select the index of the rule you wish to delete"))
        self.label_7.setText(_translate("MainWindow", "_______________________________________________________"))
